---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-yanlord
  namespace: yanlord
spec:
  hard:
    pods: "30"
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-monitoring
  namespace: monitoring
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-logging
  namespace: logging
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits-default-yanlord
  namespace: yanlord
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits-default-monitoring
  namespace: monitoring
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits-default-logging
  namespace: logging
spec:
  limits:
    - type: Container
      default:
        cpu: "300m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
